using CsvHelper.Configuration;
using FundraisinApp_Integration.Plugins.Entities.Integration_Data_Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FundraisinApp_IntegrationPlugin.FundraisinApp_Integration.Plugins.Entities.Integration_Data_Model
{
    public class DonationModelMap : ClassMap<DonationModel>
    {
        public DonationModelMap()
        {
            Map(m => m.Total_records).Name("total_records");
            Map(m => m.Donation_id).Name("donation_id");
            Map(m => m.Event_id).Name("event_id");
            Map(m => m.Org_id).Name("org_id");
            Map(m => m.Team_id).Name("team_id");
            Map(m => m.Member_id).Name("member_id");
            Map(m => m.Cause_id).Name("cause_id");
            Map(m => m.Fbuser_id).Name("fbuser_id");
            Map(m => m.Fbuser_pic).Name("fbuser_pic");
            Map(m => m.History_id).Name("history_id");
            Map(m => m.Charity_id).Name("charity_id");
            Map(m => m.Page_id).Name("page_id");
            Map(m => m.Event_page_id).Name("event_page_id");
            Map(m => m.Smscode_id).Name("smscode_id");
            Map(m => m.Sale_id).Name("sale_id");
            Map(m => m.Sale_item_id).Name("sale_item_id");
            Map(m => m.Product_id).Name("product_id");
            Map(m => m.Raffle_sale_id).Name("raffle_sale_id");
            Map(m => m.Matched_id).Name("matched_id");
            Map(m => m.Related_donation_id).Name("related_donation_id");
            Map(m => m.Donation_hash).Name("donation_hash");
            Map(m => m.Donation_type).Name("donation_type");
            Map(m => m.Campaign_id).Name("campaign_id");
            Map(m => m.Donation_frequency).Name("donation_frequency");
            Map(m => m.Donation_period).Name("donation_period");
            Map(m => m.Number_donations).Name("number_donations");
            Map(m => m.Donation_reason).Name("donation_reason");
            Map(m => m.Donation_reason_for).Name("donation_reason_for");
            Map(m => m.Donation_interval).Name("donation_interval");
            Map(m => m.Display_on).Name("display_on");
            Map(m => m.D_photo).Name("d_photo");
            Map(m => m.D_title).Name("d_title");
            Map(m => m.D_fname).Name("d_fname");
            Map(m => m.D_lname).Name("d_lname");
            Map(m => m.D_lname_prefix).Name("d_lname_prefix");
            Map(m => m.D_organisation).Name("d_organisation");
            Map(m => m.D_email).Name("d_email");
            Map(m => m.Is_fundraiser_email).Name("is_fundraiser_email");
            Map(m => m.Care_of_email).Name("care_of_email");
            Map(m => m.D_optin).Name("d_optin");
            Map(m => m.D_external_optout).Name("d_external_optout");
            Map(m => m.D_external_optout_date).Name("d_external_optout_date");
            Map(m => m.D_optin_email).Name("d_optin_email");
            Map(m => m.D_optin_sms).Name("d_optin_sms");
            Map(m => m.D_optin_post).Name("d_optin_post");
            Map(m => m.D_optin_phone).Name("d_optin_phone");
            Map(m => m.D_optin_text).Name("d_optin_text");
            Map(m => m.D_optin_charity).Name("d_optin_charity");
            Map(m => m.D_optin_fees).Name("d_optin_fees");
            Map(m => m.D_optin_fees_rate).Name("d_optin_fees_rate");
            Map(m => m.D_fee).Name("d_fee");
            Map(m => m.D_gender).Name("d_gender");
            Map(m => m.D_language).Name("d_language");
            Map(m => m.D_dob).Name("d_dob");
            Map(m => m.D_address_unit).Name("d_address_unit");
            Map(m => m.D_address_number).Name("d_address_number");
            Map(m => m.D_address_street).Name("d_address_street");
            Map(m => m.D_address_2).Name("d_address_2");
            Map(m => m.D_address_suburb).Name("d_address_suburb");
            Map(m => m.D_address_pcode).Name("d_address_pcode");
            Map(m => m.D_address_state).Name("d_address_state");
            Map(m => m.D_address_country).Name("d_address_country");
            Map(m => m.D_address_dpid).Name("d_address_dpid");
            Map(m => m.D_address_barcode).Name("d_address_barcode");
            Map(m => m.D_phone).Name("d_phone");
            Map(m => m.D_phone_home).Name("d_phone_home");
            Map(m => m.D_phone_work).Name("d_phone_work");
            Map(m => m.D_phone_mobile).Name("d_phone_mobile");
            Map(m => m.D_phone_mobile_suffix).Name("d_phone_mobile_suffix");
            Map(m => m.D_comments).Name("d_comments");
            Map(m => m.D_response).Name("d_response");
            Map(m => m.D_leave_message).Name("d_leave_message");
            Map(m => m.D_display_name).Name("d_display_name");
            Map(m => m.D_receipt).Name("d_receipt");
            Map(m => m.D_anonymous).Name("d_anonymous");
            Map(m => m.D_amount).Name("d_amount");
            Map(m => m.D_amount_local).Name("d_amount_local");
            Map(m => m.D_currency).Name("d_currency");
            Map(m => m.D_currency_rate).Name("d_currency_rate");
            Map(m => m.D_currency_platform_rate).Name("d_currency_platform_rate");
            Map(m => m.D_amount_free).Name("d_amount_free");
            Map(m => m.D_amount_sel).Name("d_amount_sel");
            Map(m => m.Gateway_customer_ref).Name("gateway_customer_ref");
            Map(m => m.Gateway_card_ref).Name("gateway_card_ref");
            Map(m => m.Po_number).Name("po_number");
            Map(m => m.Tax_ref).Name("tax_ref");
            Map(m => m.Payment_intent_id).Name("payment_intent_id");
            Map(m => m.Payment_intent_created).Name("payment_intent_created");
            Map(m => m.Stripe_payment_method).Name("stripe_payment_method");
            Map(m => m.Card_type).Name("card_type");
            Map(m => m.Card_country).Name("card_country");
            Map(m => m.Card_brand).Name("card_brand");
            Map(m => m.Payment_method).Name("payment_method");
            Map(m => m.Card_number).Name("card_number");
            Map(m => m.Card_name).Name("card_name");
            Map(m => m.Card_expiry).Name("card_expiry");
            Map(m => m.Cheque_name).Name("cheque_name");
            Map(m => m.Cheque_number).Name("cheque_number");
            Map(m => m.Eft_reference).Name("eft_reference");
            Map(m => m.Is_eft).Name("is_eft");
            Map(m => m.Bsb_number).Name("bsb_number");
            Map(m => m.Account_name).Name("account_name");
            Map(m => m.Account_number).Name("account_number");
            Map(m => m.Date_paid).Name("date_paid");
            Map(m => m.Date_banked).Name("date_banked");
            Map(m => m.D_status).Name("d_status");
            Map(m => m.D_receipt_num).Name("d_receipt_num");
            Map(m => m.D_receipt_sent).Name("d_receipt_sent");
            Map(m => m.Is_mobile).Name("is_mobile");
            Map(m => m.Is_donation).Name("is_donation");
            Map(m => m.Is_profile_donation).Name("is_profile_donation");
            Map(m => m.D_refund_amount).Name("d_refund_amount");
            Map(m => m.D_refund_amount_local).Name("d_refund_amount_local");
            Map(m => m.D_refund_reason).Name("d_refund_reason");
            Map(m => m.D_refund_date).Name("d_refund_date");
            Map(m => m.D_reissue_date).Name("d_reissue_date");
            Map(m => m.Gift_aid).Name("gift_aid");
            Map(m => m.Sent_thanks).Name("sent_thanks");
            Map(m => m.In_memory).Name("in_memory");
            Map(m => m.In_memory_title).Name("in_memory_title");
            Map(m => m.In_memory_fname).Name("in_memory_fname");
            Map(m => m.In_memory_lname).Name("in_memory_lname");
            Map(m => m.In_memory_email).Name("in_memory_email");
            Map(m => m.In_memory_address1).Name("in_memory_address1");
            Map(m => m.In_memory_address2).Name("in_memory_address2");
            Map(m => m.In_memory_card).Name("in_memory_card");
            Map(m => m.In_memory_card_to).Name("in_memory_card_to");
            Map(m => m.Ecard_first_name).Name("ecard_first_name");
            Map(m => m.Ecard_last_name).Name("ecard_last_name");
            Map(m => m.Ecard_email).Name("ecard_email");
            Map(m => m.Ecard_comments).Name("ecard_comments");
            Map(m => m.Ecard_address).Name("ecard_address");
            Map(m => m.Kw_address).Name("kw_address");
            Map(m => m.Donor_lat).Name("donor_lat");
            Map(m => m.Donor_lng).Name("donor_lng");
            Map(m => m.Donor_ip).Name("donor_ip");
            Map(m => m.Donor_useragent).Name("donor_useragent");
            Map(m => m.Utm_campaign).Name("utm_campaign");
            Map(m => m.Utm_source).Name("utm_source");
            Map(m => m.Utm_medium).Name("utm_medium");
            Map(m => m.Utm_content).Name("utm_content");
            Map(m => m.Utm_term).Name("utm_term");
            Map(m => m.Donation_tags).Name("donation_tags");
            Map(m => m.Donor_mfa_code).Name("donor_mfa_code");
            Map(m => m.Crm_donor_id).Name("crm_donor_id");
            Map(m => m.Fb_donation_id).Name("fb_donation_id");
            Map(m => m.Funraisin_synced).Name("funraisin_synced");
            Map(m => m.Ecrm_customer_id).Name("ecrm_customer_id");
            Map(m => m.Scrm_customer_id).Name("scrm_customer_id");
            Map(m => m.Last_logged_in).Name("last_logged_in");
            Map(m => m.Ecrm_last_synced_date).Name("ecrm_last_synced_date");
            Map(m => m.Scrm_last_synced_date).Name("scrm_last_synced_date");
            Map(m => m.Dtd).Name("dtd");
            Map(m => m.Dtd_processed).Name("dtd_processed");
            Map(m => m.Dtd_company_id).Name("dtd_company_id");
            Map(m => m.Dtd_company_name).Name("dtd_company_name");
            Map(m => m.Dtd_identifier).Name("dtd_identifier");
            Map(m => m.Last_updated).Name("last_updated");
            Map(m => m.Date_created).Name("date_created");
        }
    }
}
