// Decompiled with JetBrains decompiler
// Type: FundraisinApp_Integration.Plugins.Entities.Integration_Data_Model.DonationModel
// Assembly: FundraisinApp-Integration.Plugin, Version=1.0.0.0, Culture=neutral, PublicKeyToken=be17da884c09fb48
// MVID: A80D178E-91E0-4361-9810-5F6936033CCA
// Assembly location: C:\Users\Nico Benito\Downloads\NicoTestSolution_1_0_0_2\PluginAssemblies\FundraisinApp-IntegrationPlugin-AD40DC3F-2002-4C54-899F-1599020D0AFB\FundraisinApp-IntegrationPlugin.dll

using System;

#nullable disable
namespace FundraisinApp_Integration.Plugins.Entities.Integration_Data_Model
{
  public class DonationModel
  {
        public string Total_records { get; set; }
        public string Donation_id { get; set; }
        public string Event_id { get; set; }
        public string Org_id { get; set; }
        public string Team_id { get; set; }
        public string Member_id { get; set; }
        public string Cause_id { get; set; }
        public string Fbuser_id { get; set; }
        public string Fbuser_pic { get; set; }
        public string History_id { get; set; }
        public string Charity_id { get; set; }
        public string Page_id { get; set; }
        public string Event_page_id { get; set; }
        public string Smscode_id { get; set; }
        public string Sale_id { get; set; }
        public string Sale_item_id { get; set; }
        public string Product_id { get; set; }
        public string Raffle_sale_id { get; set; }
        public string Matched_id { get; set; }
        public string Related_donation_id { get; set; }
        public string Donation_hash { get; set; }
        public string Donation_type { get; set; }
        public string Campaign_id { get; set; }
        public string Donation_frequency { get; set; }
        public string Donation_period { get; set; }
        public string Number_donations { get; set; }
        public string Donation_reason { get; set; }
        public string Donation_reason_for { get; set; }
        public string Donation_interval { get; set; }
        public string Display_on { get; set; }
        public string D_photo { get; set; }
        public string D_title { get; set; }
        public string D_fname { get; set; }
        public string D_lname { get; set; }
        public string D_lname_prefix { get; set; }
        public string D_organisation { get; set; }
        public string D_email { get; set; }
        public string Is_fundraiser_email { get; set; }
        public string Care_of_email { get; set; }
        public string D_optin { get; set; }
        public string D_external_optout { get; set; }
        public string D_external_optout_date { get; set; }
        public string D_optin_email { get; set; }
        public string D_optin_sms { get; set; }
        public string D_optin_post { get; set; }
        public string D_optin_phone { get; set; }
        public string D_optin_text { get; set; }
        public string D_optin_charity { get; set; }
        public string D_optin_fees { get; set; }
        public string D_optin_fees_rate { get; set; }
        public string D_fee { get; set; }
        public string D_gender { get; set; }
        public string D_language { get; set; }
        public string D_dob { get; set; }
        public string D_address_unit { get; set; }
        public string D_address_number { get; set; }
        public string D_address_street { get; set; }
        public string D_address_2 { get; set; }
        public string D_address_suburb { get; set; }
        public string D_address_pcode { get; set; }
        public string D_address_state { get; set; }
        public string D_address_country { get; set; }
        public string D_address_dpid { get; set; }
        public string D_address_barcode { get; set; }
        public string D_phone { get; set; }
        public string D_phone_home { get; set; }
        public string D_phone_work { get; set; }
        public string D_phone_mobile { get; set; }
        public string D_phone_mobile_suffix { get; set; }
        public string D_comments { get; set; }
        public string D_response { get; set; }
        public string D_leave_message { get; set; }
        public string D_display_name { get; set; }
        public string D_receipt { get; set; }
        public string D_anonymous { get; set; }
        public string D_amount { get; set; }
        public string D_amount_local { get; set; }
        public string D_currency { get; set; }
        public string D_currency_rate { get; set; }
        public string D_currency_platform_rate { get; set; }
        public string D_amount_free { get; set; }
        public string D_amount_sel { get; set; }
        public string Gateway_customer_ref { get; set; }
        public string Gateway_card_ref { get; set; }
        public string Po_number { get; set; }
        public string Tax_ref { get; set; }
        public string Payment_intent_id { get; set; }
        public string Payment_intent_created { get; set; }
        public string Stripe_payment_method { get; set; }
        public string Card_type { get; set; }
        public string Card_country { get; set; }
        public string Card_brand { get; set; }
        public string Payment_method { get; set; }
        public string Card_number { get; set; }
        public string Card_name { get; set; }
        public string Card_expiry { get; set; }
        public string Cheque_name { get; set; }
        public string Cheque_number { get; set; }
        public string Eft_reference { get; set; }
        public string Is_eft { get; set; }
        public string Bsb_number { get; set; }
        public string Account_name { get; set; }
        public string Account_number { get; set; }
        public string Date_paid { get; set; }
        public string Date_banked { get; set; }
        public string D_status { get; set; }
        public string D_receipt_num { get; set; }
        public string D_receipt_sent { get; set; }
        public string Is_mobile { get; set; }
        public string Is_donation { get; set; }
        public string Is_profile_donation { get; set; }
        public string D_refund_amount { get; set; }
        public string D_refund_amount_local { get; set; }
        public string D_refund_reason { get; set; }
        public string D_refund_date { get; set; }
        public string D_reissue_date { get; set; }
        public string Gift_aid { get; set; }
        public string Sent_thanks { get; set; }
        public string In_memory { get; set; }
        public string In_memory_title { get; set; }
        public string In_memory_fname { get; set; }
        public string In_memory_lname { get; set; }
        public string In_memory_email { get; set; }
        public string In_memory_address1 { get; set; }
        public string In_memory_address2 { get; set; }
        public string In_memory_card { get; set; }
        public string In_memory_card_to { get; set; }
        public string Ecard_first_name { get; set; }
        public string Ecard_last_name { get; set; }
        public string Ecard_email { get; set; }
        public string Ecard_comments { get; set; }
        public string Ecard_address { get; set; }
        public string Kw_address { get; set; }
        public string Donor_lat { get; set; }
        public string Donor_lng { get; set; }
        public string Donor_ip { get; set; }
        public string Donor_useragent { get; set; }
        public string Utm_campaign { get; set; }
        public string Utm_source { get; set; }
        public string Utm_medium { get; set; }
        public string Utm_content { get; set; }
        public string Utm_term { get; set; }
        public string Donation_tags { get; set; }
        public string Donor_mfa_code { get; set; }
        public string Crm_donor_id { get; set; }
        public string Fb_donation_id { get; set; }
        public string Funraisin_synced { get; set; }
        public string Ecrm_customer_id { get; set; }
        public string Scrm_customer_id { get; set; }
        public string Last_logged_in { get; set; }
        public string Ecrm_last_synced_date { get; set; }
        public string Scrm_last_synced_date { get; set; }
        public string Dtd { get; set; }
        public string Dtd_processed { get; set; }
        public string Dtd_company_id { get; set; }
        public string Dtd_company_name { get; set; }
        public string Dtd_identifier { get; set; }
        public string Last_updated { get; set; }
        public string Date_created { get; set; }
    }
}
