using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FundraisinApp_IntegrationPlugin.FundraisinApp_Integration.Plugins.Entities.Integration_Data_Model
{
    public class ParticipantEventModel
    {
        public string Total_Records { get; set; }
        public string History_Id { get; set; }
        public string Member_Id { get; set; }
        public string Event_Id { get; set; }
        public string Org_Id { get; set; }
        public string Team_Id { get; set; }
        public string Charity_Id { get; set; }
        public string Group_Id { get; set; }
        public string Table_Id { get; set; }
        public string Wave_Id { get; set; }
        public string Ticket_Id { get; set; }
        public string Invited_Member_Id { get; set; }
        public string Paid_Member_Id { get; set; }
        public string Managed_Member_Id { get; set; }
        public string History_Type { get; set; }
        public string Member_Type { get; set; }
        public string Bib_Number { get; set; }
        public string Seat_Number { get; set; }
        public string Is_Active { get; set; }
        public string Is_Additional { get; set; }
        public string Is_Archived { get; set; }
        public string Is_Fundraising { get; set; }
        public string In_Search { get; set; }
        public string Is_Team { get; set; }
        public string Is_Featured { get; set; }
        public string Is_Attending { get; set; }
        public string Date_Attending { get; set; }
        public string Has_Checkedout { get; set; }
        public string Date_Checkedout { get; set; }
        public string Done_PersonalDetails { get; set; }
        public string Done_EventOptions { get; set; }
        public string Done_Fundraising { get; set; }
        public string Done_TeamDetails { get; set; }
        public string Conf_Key { get; set; }
        public string Entry_Code { get; set; }
        public string Promo_Id { get; set; }
        public string Paypal_Token { get; set; }
        public string Stripe_Source_Id { get; set; }
        public string Payment_Intent_Id { get; set; }
        public string Payment_Intent_Created { get; set; }
        public string Insurance_Quote_Id { get; set; }
        public string M_Optin_Insurance { get; set; }
        public string Ticket { get; set; }
        public string Number_Tickets { get; set; }
        public string Number_Tables { get; set; }
        public string Team_Access { get; set; }
        public string Org_Access { get; set; }
        public string M_Display_Reason { get; set; }
        public string M_Target { get; set; }
        public string M_Target_Local { get; set; }
        public string M_Target_Distance { get; set; }
        public string M_Target_Duration { get; set; }
        public string M_Target_Steps { get; set; }
        public string M_Challenge_Mode { get; set; }
        public string M_Comments { get; set; }
        public string M_Reason { get; set; }
        public string M_Stream { get; set; }
        public string M_Stream_Username { get; set; }
        public string M_Stream_Type { get; set; }
        public string M_Stream_Comments { get; set; }
        public string M_Codeblock { get; set; }
        public string M_Codeblock_Mobile { get; set; }
        public string M_Page_Title { get; set; }
        public string M_CoverPhoto { get; set; }
        public string M_Event_Photo { get; set; }
        public string Show_Gallery { get; set; }
        public string Show_Social { get; set; }
        public string M_Donation_Amount { get; set; }
        public string M_Donation_Amount_Local { get; set; }
        public string M_Donation_Amount_Sel { get; set; }
        public string M_Donation_Amount_Free { get; set; }
        public string M_Donation_Po { get; set; }
        public string M_Donation_Fee { get; set; }
        public string M_Donation_Fee_Optin { get; set; }
        public string M_Donation_Fee_Rate { get; set; }
        public string Is_Paid { get; set; }
        public string Is_Complete { get; set; }
        public string Date_Completed { get; set; }
        public string Total_Paid { get; set; }
        public string Total_Paid_Local { get; set; }
        public string M_Currency { get; set; }
        public string M_Currency_Rate { get; set; }
        public string M_Currency_Platform_Rate { get; set; }
        public string Total_Paid_Entry { get; set; }
        public string Total_Paid_Entry_Local { get; set; }
        public string Total_Paid_Ticket { get; set; }
        public string Total_Paid_Paypal { get; set; }
        public string Total_Paid_Card { get; set; }
        public string Total_Paid_Extra { get; set; }
        public string Total_Paid_Merchandise { get; set; }
        public string Total_Paid_Merchandise_Local { get; set; }
        public string Total_Paid_Donation { get; set; }
        public string Total_Paid_Donation_Local { get; set; }
        public string Total_Paid_Delivery { get; set; }
        public string Total_Paid_Delivery_Local { get; set; }
        public string Total_Paid_Insurance { get; set; }
        public string Total_Paid_Insurance_Local { get; set; }
        public string Total_Paid_Fees { get; set; }
        public string Total_Paid_Tax { get; set; }
        public string M_Refund { get; set; }
        public string M_Refund_Amount { get; set; }
        public string M_Refund_Reason { get; set; }
        public string M_Refund_Date { get; set; }
        public string M_Receipt_Sent { get; set; }
        public string M_Confirmation_Sent { get; set; }
        public string Payment_Method { get; set; }
        public string Eft_Reference { get; set; }
        public string Payment_Source { get; set; }
        public string Payment_Failed { get; set; }
        public string Payment_Failed_Reason { get; set; }
        public string Po_Number { get; set; }
        public string Tax_Ref { get; set; }
        public string Card_Type { get; set; }
        public string Card_Country { get; set; }
        public string Card_Brand { get; set; }
        public string Card_Number { get; set; }
        public string Card_Expiry { get; set; }
        public string Card_Name { get; set; }
        public string Date_Paid { get; set; }
        public string Bsb_Number { get; set; }
        public string Account_Number { get; set; }
        public string Cheque_Name { get; set; }
        public string Money_Order_Number { get; set; }
        public string Sort_Order { get; set; }
        public string Activity_Lat { get; set; }
        public string Activity_UserAgent { get; set; }
        public string Activity_Ip { get; set; }
        public string Activity_Lng { get; set; }
        public string Card_Token { get; set; }
        public string Customer_Token { get; set; }
        public string Utm_Campaign { get; set; }
        public string Utm_Source { get; set; }
        public string Utm_Medium { get; set; }
        public string Utm_Content { get; set; }
        public string Utm_Term { get; set; }
        public string M_Optin_Event { get; set; }
        public string M_Optin_Event_Email { get; set; }
        public string M_Optin_Event_Sms { get; set; }
        public string M_Optin_Event_Post { get; set; }
        public string M_Optin_Event_Phone { get; set; }
        public string M_Optout_Event_Triggers { get; set; }
        public string M_Optout_Event_Triggers_Date { get; set; }
        public string M_Optin_Event_Text { get; set; }
        public string M_Thanks_Message { get; set; }
        public string M_Thanks_Video { get; set; }
        public string M_Thanks_Image { get; set; }
        public string In_Memory_Name { get; set; }
        public string In_Memory_Next_Of_Kin { get; set; }
        public string In_Memory_Relationship { get; set; }
        public string Admin_Tags { get; set; }
        public string Fb_Fundraiser_Id { get; set; }
        public string Twitch_Id { get; set; }
        public string Total_Raised { get; set; }
        public string Total_Raised_Local { get; set; }
        public string Total_Steps { get; set; }
        public string Total_Distance { get; set; }
        public string Total_Duration { get; set; }
        public string Total_Spent { get; set; }
        public string Total_Amount_Approved { get; set; }
        public string Total_Amount_Local { get; set; }
        public string Is_Deleted { get; set; }
        public string Source { get; set; }
        public string Source_Id { get; set; }
        public string Updated_By { get; set; }
        public string Updated_Date { get; set; }
        public string Date_Created { get; set; }
        public string Record_Hash { get; set; }
    }
}
